name: e_hujjat
description: "e_hujjat"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  windows_notification: ^1.3.0
  http: ^1.2.2
  path_provider: ^2.1.5
  window_manager: ^0.4.3
  email_validator: ^3.0.0
  postgres: ^3.4.8
  shared_preferences: ^2.3.5
  flutter_local_notifications: ^18.0.1
  fl_chart: ^0.70.0
  system_tray: ^2.0.3
  bitsdojo_window: ^0.1.6
  english_words: ^4.0.0
  intl: ^0.19.0
  dynamic_height_grid_view: ^0.0.4
  lottie: ^3.3.0
  table_calendar: ^3.1.3
  syncfusion_flutter_calendar: ^28.1.38
  flutter_localization: ^0.3.1
  responsive_grid_list: ^1.4.0
  simple_grid: ^0.1.5
  flutter_svg: ^2.0.17
  progress_bar_chart: ^0.0.12
  accordion: ^2.6.0
  one_clock: ^2.0.1
  calendar_date_picker2: ^1.1.8
  easy_localization: ^3.0.7
  go_router: ^14.6.3
  provider: ^6.1.2
  dio: ^5.7.0
  logger: ^2.5.0
  top_snackbar_flutter: ^3.1.0
  elegant_notification: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/  
    - assets/fonts/ 
    - assets/lotties/ 
    - assets/translations/ 

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf   